In [1]:
# Import librairies:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

### Financial Statement documents:

In [2]:
# Balance Sheet:
balance_sheet=pd.read_excel(r'Financial Statement(SID).xlsx',sheet_name= 'Balance Sheet annualy')
balance_sheet=balance_sheet.iloc[2:,1:-1].reset_index(drop=True)

# Rename columns:

balance_sheet.columns=balance_sheet.columns.str.replace('FY','',regex=False)
balance_sheet

,Fiscal Year,2024,2023,2022,2021,2020
0,Cash & Equivalents,723.41,768.14,851.64,979.88,865.75
1,Trading Asset Securities,-,9.92,24.41,1.63,1.38
2,Cash & Short-Term Investments,723.41,778.06,876.04,981.5,867.13
3,Cash Growth,-7.02%,-11.19%,-10.75%,13.19%,47.66%
4,Accounts Receivable,1752,1339,1043,650.51,721.83
5,Other Receivables,186.19,216.8,161.48,125.36,104.3
6,Receivables,1939,1555,1204,775.87,826.14
7,Inventory,1012,975.67,1012,641.19,548.34
8,Prepaid Expenses,-,-,-,1.3,0.1
9,Other Current Assets,2.45,-,-,-,-
10,Total Current Assets,3676,3309,3092,2400,2242
11,"Property, Plant & Equipment",1431,1372,1273,1283,1341
12,Other Intangible Assets,2.92,4.42,5.67,6.85,2.42
13,Long-Term Deferred Tax Assets,156.08,-,1.27,159.58,155.19
14,Other Long-Term Assets,39.95,198.03,208,43.45,39.95
15,Total Assets,5306,4883,4581,3892,3781
16,Accounts Payable,2329,2046,1779,1060,1089
17,Accrued Expenses,-,492,385.2,362.81,282.94
18,Other Current Liabilities,624.49,27.57,27.7,27.6,29.29
19,Total Current Liabilities,2953,2566,2192,1451,1402
20,Long-Term Leases,100.02,109.76,109.05,115.71,123.19
21,Long-Term Deferred Tax Liabilities,205.7,216.16,230.73,211.2,228.47
22,Other Long-Term Liabilities,75.02,77.66,80.31,82.95,87.35
23,Total Liabilities,3426,3067,2734,2002,1966
24,Common Stock,390,390,390,390,390
25,Additional Paid-In Capital,1.6,1.6,1.6,1.6,1.6
26,Retained Earnings,183.28,109.88,127.13,147.57,19.35
27,Comprehensive Income & Other,1302,1312,1326,1349,1402
28,Total Common Equity,1877,1814,1845,1888,1813
29,Minority Interest,2.78,2.55,2.28,2.01,1.76
30,Shareholders' Equity,1879,1816,1847,1890,1814
31,Total Liabilities & Equity,5306,4883,4581,3892,3781
32,Total Debt,100.02,109.76,109.05,115.71,123.19
33,Net Cash (Debt),623.39,668.3,767,865.79,743.94
34,Net Cash Growth,-6.72%,-12.87%,-11.41%,16.38%,47.60%
35,Net Cash Per Share,159.82,171.36,196.67,222.00,190.75
36,Filing Date Shares Outstanding,3.9,3.9,3.9,3.9,3.9
37,Total Common Shares Outstanding,3.9,3.9,3.9,3.9,3.9
38,Working Capital,723.19,743.28,900.08,949.16,840.14
39,Book Value Per Share,481.17,465.11,473.02,484.14,464.76
40,Tangible Book Value,1874,1810,1839,1881,1810
41,Tangible Book Value Per Share,480.42,463.98,471.56,482.38,464.14
42,Land,-,268.4,267.9,266.2,-
43,Buildings,-,752,749,727.69,-
44,Machinery,-,3963,3740,3641,-
45,Construction In Progress,-,39.3,50,46.51,-

In [3]:
# Income Statement:

income_statement=pd.read_excel(r'Financial Statement(SID).xlsx',sheet_name='Income Statement annualy')
income_statement=income_statement.iloc[2:,1:-1].reset_index(drop=True)

# Rename columns:

income_statement.columns=income_statement.columns.str.replace('FY','',regex=False)
income_statement

,Fiscal Year,2024,2023,2022,2021,2020
0,Operating Revenue,5495,4996,4888,4494,3153
1,Revenue,5495,4996,4888,4494,3153
2,Revenue Growth (YoY),9.98%,2.20%,8.77%,42.54%,-12.96%
3,Cost of Revenue,4391,4088,4286,3733,2661
4,Gross Profit,1103,907.9,602.19,760.41,491.38
5,"Selling, General & Admin",585.39,509.53,475.32,485.4,395.11
6,Other Operating Expenses,142.73,144.79,-191.61,-64.88,-37.87
7,Operating Expenses,881.02,790.96,439.4,593.68,513.24
8,Operating Income,222.33,116.94,162.79,166.73,-21.86
9,Interest Expense,-15.59,-34.3,-12.55,-9.08,-8.44
10,Interest & Investment Income,4.69,10.78,14.66,12.39,13.52
11,Currency Exchange Gain (Loss),-,11.4,-33.9,-1.8,-7.61
12,Other Non Operating Income (Expenses),6.53,-14.47,20.75,-7.14,0.6
13,EBT Excluding Unusual Items,217.96,90.35,151.75,161.11,-23.79
14,Gain (Loss) on Sale of Assets,0.15,0.48,-0.08,-,1.96
15,Other Unusual Items,-9.61,2.24,0.24,2.62,-8.79
16,Pretax Income,208.5,93.06,151.91,163.73,-30.62
17,Income Tax Expense,66.76,27.81,65.76,55.67,-2.71
18,Earnings From Continuing Operations,141.74,65.25,86.15,108.06,-27.91
19,Minority Interest in Earnings,-0.5,-0.17,-0.22,-0.29,-0.14
20,Net Income,141.24,65.08,85.93,107.77,-28.05
21,Net Income to Common,141.24,65.08,85.93,107.77,-28.05
22,Net Income Growth,117.03%,-24.27%,-20.27%,-,-
23,Shares Outstanding (Basic),4,4,4,4,4
24,Shares Outstanding (Diluted),4,4,4,4,4
25,Shares Change (YoY),0.01%,-,-,-,-
26,EPS (Basic),36.21,16.69,22.03,27.63,-7.19
27,EPS (Diluted),36.21,16.69,22.03,27.63,-7.19
28,EPS Growth,117.00%,-24.26%,-20.27%,-,-
29,Free Cash Flow,63.47,67.31,38.66,154.68,246.14
30,Free Cash Flow Per Share,16.27,17.26,9.91,39.66,63.11
31,Dividend Per Share,39.000,21.000,30.000,38.000,7.000
32,Dividend Growth,85.71%,-30.00%,-21.05%,442.86%,-
33,Gross Margin,20.08%,18.17%,12.32%,16.92%,15.59%
34,Operating Margin,4.05%,2.34%,3.33%,3.71%,-0.69%
35,Profit Margin,2.57%,1.30%,1.76%,2.40%,-0.89%
36,Free Cash Flow Margin,1.16%,1.35%,0.79%,3.44%,7.81%
37,EBITDA,368.15,245.76,313.35,303.73,116.15
38,EBITDA Margin,6.70%,4.92%,6.41%,6.76%,3.68%
39,D&A For EBITDA,145.83,128.82,150.55,137,138
40,EBIT,222.33,116.94,162.79,166.73,-21.86
41,EBIT Margin,4.05%,2.34%,3.33%,3.71%,-0.69%
42,Effective Tax Rate,32.02%,29.88%,43.29%,34.00%,-
43,Revenue as Reported,5400,4883,5124,4605,3238

In [4]:
# Cash Flow Statement:
cash_flow_statement=pd.read_excel(r'Financial Statement(SID).xlsx',sheet_name='Cash Flow annualy')
cash_flow_statement=cash_flow_statement.iloc[2:,1:-1].reset_index(drop=True)

# Rename columns:

cash_flow_statement.columns=cash_flow_statement.columns.str.replace('FY','',regex=False)
cash_flow_statement

,Fiscal Year,2024,2023,2022,2021,2020
0,Net Income,141.24,65.08,85.93,107.77,-28.05
1,Depreciation & Amortization,145.83,143.22,164.15,149.7,150.8
2,Other Amortization,-,2,2,1.6,1.6
3,Loss (Gain) From Sale of Assets,-0.15,-0.48,0.08,-1.17,-1.96
4,Other Operating Activities,11.82,34.88,-8.76,-5.75,-1.83
5,Change in Other Net Operating Assets,-34.31,58.6,-57.33,-0.99,263.71
6,Operating Cash Flow,264.42,303.31,186.07,251.15,384.27
7,Operating Cash Flow Growth,-12.82%,63.01%,-25.91%,-34.64%,-11.03%
8,Capital Expenditures,-200.95,-236,-147.41,-96.47,-138.13
9,"Sale of Property, Plant & Equipment",0.15,0.48,-,1.37,2.61
10,Investment in Securities,0.01,-,-0.02,-,0.02
11,Other Investing Activities,-15.59,-34.3,-12.55,-9.08,-8.44
12,Investing Cash Flow,-216.38,-269.83,-159.98,-104.18,-143.94
13,Long-Term Debt Issued,-,0.71,-,-,72.96
14,Long-Term Debt Repaid,-10.69,-,-6.66,-7.48,-
15,Net Debt Issued (Repaid),-10.69,0.71,-6.66,-7.48,72.96
16,Common Dividends Paid,-81.91,-117,-148.2,-27.26,-
17,Other Financing Activities,-0.18,-0.69,0.53,1.9,-1.01
18,Financing Cash Flow,-92.77,-116.98,-154.33,-32.84,71.95
19,Net Cash Flow,-44.72,-83.5,-128.24,114.13,312.29
20,Free Cash Flow,63.47,67.31,38.66,154.68,246.14
21,Free Cash Flow Growth,-5.70%,74.11%,-75.01%,-37.16%,-35.17%
22,Free Cash Flow Margin,1.16%,1.35%,0.79%,3.44%,7.81%
23,Free Cash Flow Per Share,16.27,17.26,9.91,39.66,63.11
24,Cash Interest Paid,15.59,34.3,12.55,9.08,8.44
25,Cash Income Tax Paid,78.51,41.89,64.51,75.66,18.04
26,Levered Free Cash Flow,39.53,19.69,56.26,158.73,264.51
27,Unlevered Free Cash Flow,49.27,41.13,64.1,164.4,269.78
28,Change in Net Working Capital,34.55,-58.82,56.39,-5.36,-269.17

In [5]:
ratios_statement=pd.read_excel(r'Financial Statement(SID).xlsx',sheet_name='Ratios annualy')
ratios_statement=ratios_statement.iloc[2:,1:-1].reset_index(drop=True)
ratios_statement.columns=ratios_statement.columns.str.replace('FY','',regex=False)
ratios_statement

,Fiscal Year,Current,2024,2023,2022,2021,2020
0,Market Capitalization,6903,3837,2574,2028,2399,1170
1,Market Cap Growth,75.70%,49.08%,26.92%,-15.45%,105.00%,20.00%
2,Enterprise Value,6282,3171,1902,1162,1608,549
3,Last Close Price,1770.00,983.90,644.65,482.47,541.70,261.18
4,PE Ratio,48.88,27.17,39.55,23.60,22.26,-
5,Forward PE,77.46,46.41,28.08,14.61,25.91,-
6,PS Ratio,1.26,0.70,0.52,0.42,0.53,0.37
7,PB Ratio,3.68,2.04,1.42,1.10,1.27,0.65
8,P/TBV Ratio,2.05,2.05,1.42,1.10,1.27,0.65
9,P/FCF Ratio,108.76,60.46,38.24,52.46,15.51,4.75
10,P/OCF Ratio,14.51,14.51,8.49,10.90,9.55,3.05
11,EV/Sales Ratio,1.14,0.58,0.38,0.24,0.36,0.17
12,EV/EBITDA Ratio,17.06,8.62,7.74,3.71,5.30,4.73
13,EV/EBIT Ratio,28.26,14.27,16.26,7.14,9.65,-
14,EV/FCF Ratio,98.98,49.97,28.25,30.06,10.40,2.23
15,Debt / Equity Ratio,0.05,0.05,0.06,0.06,0.06,0.07
16,Debt / EBITDA Ratio,0.27,0.27,0.42,0.33,0.37,0.96
17,Debt / FCF Ratio,1.58,1.58,1.63,2.82,0.75,0.50
18,Asset Turnover,1.08,1.08,1.06,1.15,1.17,0.86
19,Inventory Turnover,4.42,4.42,4.11,5.19,6.28,5.31
20,Quick Ratio,0.90,0.90,0.91,0.95,1.21,1.21
21,Current Ratio,1.25,1.25,1.29,1.41,1.65,1.60
22,Return on Equity (ROE),7.67%,7.67%,3.56%,4.61%,5.83%,-1.52%
23,Return on Assets (ROA),2.73%,2.73%,1.54%,2.40%,2.72%,-0.37%
24,Return on Capital (ROIC),7.12%,7.12%,3.77%,5.14%,5.29%,-0.71%
25,Return on Capital Employed (ROCE),9.50%,9.50%,5.00%,6.80%,6.80%,-
26,Earnings Yield,2.05%,3.68%,2.53%,4.24%,4.49%,-2.40%
27,FCF Yield,0.92%,1.65%,2.61%,1.91%,6.45%,21.04%
28,Dividend Yield,2.02%,3.96%,3.26%,6.22%,7.02%,2.68%
29,Payout Ratio,57.99%,57.99%,179.79%,172.47%,25.30%,-
30,Buyback Yield / Dilution,-0.00%,-0.01%,-,-,-,-
31,Total Shareholder Return,2.02%,3.95%,3.26%,6.22%,7.02%,2.68%

### Transpose the Data :

##### Balance Sheet:

In [6]:
# Balance Sheet:
bs_trsp=balance_sheet.transpose()
bs_trsp=bs_trsp.reset_index(drop=False)
# sets first row as the actual column names:
bs_trsp.columns=bs_trsp.iloc[0]
# removes row 0:
bs_trsp=bs_trsp.drop(0)
bs_trsp

,Fiscal Year,Cash & Equivalents,Trading Asset Securities,Cash & Short-Term Investments,Cash Growth,Accounts Receivable,Other Receivables,Receivables,Inventory,Prepaid Expenses,...,Filing Date Shares Outstanding,Total Common Shares Outstanding,Working Capital,Book Value Per Share,Tangible Book Value,Tangible Book Value Per Share,Land,Buildings,Machinery,Construction In Progress
1,2024,723.41,-,723.41,-7.02%,1752,186.19,1939,1012,-,...,3.9,3.9,723.19,481.17,1874,480.42,-,-,-,-
2,2023,768.14,9.92,778.06,-11.19%,1339,216.8,1555,975.67,-,...,3.9,3.9,743.28,465.11,1810,463.98,268.4,752,3963,39.3
3,2022,851.64,24.41,876.04,-10.75%,1043,161.48,1204,1012,-,...,3.9,3.9,900.08,473.02,1839,471.56,267.9,749,3740,50
4,2021,979.88,1.63,981.5,13.19%,650.51,125.36,775.87,641.19,1.3,...,3.9,3.9,949.16,484.14,1881,482.38,266.2,727.69,3641,46.51
5,2020,865.75,1.38,867.13,47.66%,721.83,104.3,826.14,548.34,0.1,...,3.9,3.9,840.14,464.76,1810,464.14,-,-,-,-

In [7]:
# Convert to datetime:
bs_trsp[bs_trsp.columns[0]] = pd.to_datetime(bs_trsp.iloc[:, 0], errors='coerce')
# Set the date to December 31 of the year for all valid dates:
bs_trsp[bs_trsp.columns[0]] = bs_trsp[bs_trsp.columns[0]].dt.year.astype('int64').astype(str) + '-12-31'
bs_trsp[bs_trsp.columns[0]]=pd.to_datetime(bs_trsp[bs_trsp.columns[0]],errors='coerce')
bs_trsp

,Fiscal Year,Cash & Equivalents,Trading Asset Securities,Cash & Short-Term Investments,Cash Growth,Accounts Receivable,Other Receivables,Receivables,Inventory,Prepaid Expenses,...,Filing Date Shares Outstanding,Total Common Shares Outstanding,Working Capital,Book Value Per Share,Tangible Book Value,Tangible Book Value Per Share,Land,Buildings,Machinery,Construction In Progress
1,2024-12-31,723.41,-,723.41,-7.02%,1752,186.19,1939,1012,-,...,3.9,3.9,723.19,481.17,1874,480.42,-,-,-,-
2,2023-12-31,768.14,9.92,778.06,-11.19%,1339,216.8,1555,975.67,-,...,3.9,3.9,743.28,465.11,1810,463.98,268.4,752,3963,39.3
3,2022-12-31,851.64,24.41,876.04,-10.75%,1043,161.48,1204,1012,-,...,3.9,3.9,900.08,473.02,1839,471.56,267.9,749,3740,50
4,2021-12-31,979.88,1.63,981.5,13.19%,650.51,125.36,775.87,641.19,1.3,...,3.9,3.9,949.16,484.14,1881,482.38,266.2,727.69,3641,46.51
5,2020-12-31,865.75,1.38,867.13,47.66%,721.83,104.3,826.14,548.34,0.1,...,3.9,3.9,840.14,464.76,1810,464.14,-,-,-,-

##### Income Statement:

In [8]:
inc_trsp=income_statement.transpose().reset_index(drop=False)
# sets first row as the actual column names:
inc_trsp.columns=inc_trsp.iloc[0]
# Remove the row 0:
inc_trsp=inc_trsp.drop(0)
inc_trsp

,Fiscal Year,Operating Revenue,Revenue,Revenue Growth (YoY),Cost of Revenue,Gross Profit,"Selling, General & Admin",Other Operating Expenses,Operating Expenses,Operating Income,...,Operating Margin,Profit Margin,Free Cash Flow Margin,EBITDA,EBITDA Margin,D&A For EBITDA,EBIT,EBIT Margin,Effective Tax Rate,Revenue as Reported
1,2024,5495,5495,9.98%,4391,1103,585.39,142.73,881.02,222.33,...,4.05%,2.57%,1.16%,368.15,6.70%,145.83,222.33,4.05%,32.02%,5400
2,2023,4996,4996,2.20%,4088,907.9,509.53,144.79,790.96,116.94,...,2.34%,1.30%,1.35%,245.76,4.92%,128.82,116.94,2.34%,29.88%,4883
3,2022,4888,4888,8.77%,4286,602.19,475.32,-191.61,439.4,162.79,...,3.33%,1.76%,0.79%,313.35,6.41%,150.55,162.79,3.33%,43.29%,5124
4,2021,4494,4494,42.54%,3733,760.41,485.4,-64.88,593.68,166.73,...,3.71%,2.40%,3.44%,303.73,6.76%,137,166.73,3.71%,34.00%,4605
5,2020,3153,3153,-12.96%,2661,491.38,395.11,-37.87,513.24,-21.86,...,-0.69%,-0.89%,7.81%,116.15,3.68%,138,-21.86,-0.69%,-,3238

In [9]:
#Change data type of Fiscal Year:

inc_trsp['Fiscal Year']=pd.to_datetime(inc_trsp['Fiscal Year'], errors='coerce')
# Set the date to December 31 of the year for all valid dates:
inc_trsp['Fiscal Year']=inc_trsp['Fiscal Year'].dt.year.astype('int64').astype(str)+'-12-31'
inc_trsp['Fiscal Year']=pd.to_datetime(inc_trsp['Fiscal Year'],errors='coerce')
inc_trsp

,Fiscal Year,Operating Revenue,Revenue,Revenue Growth (YoY),Cost of Revenue,Gross Profit,"Selling, General & Admin",Other Operating Expenses,Operating Expenses,Operating Income,...,Operating Margin,Profit Margin,Free Cash Flow Margin,EBITDA,EBITDA Margin,D&A For EBITDA,EBIT,EBIT Margin,Effective Tax Rate,Revenue as Reported
1,2024-12-31,5495,5495,9.98%,4391,1103,585.39,142.73,881.02,222.33,...,4.05%,2.57%,1.16%,368.15,6.70%,145.83,222.33,4.05%,32.02%,5400
2,2023-12-31,4996,4996,2.20%,4088,907.9,509.53,144.79,790.96,116.94,...,2.34%,1.30%,1.35%,245.76,4.92%,128.82,116.94,2.34%,29.88%,4883
3,2022-12-31,4888,4888,8.77%,4286,602.19,475.32,-191.61,439.4,162.79,...,3.33%,1.76%,0.79%,313.35,6.41%,150.55,162.79,3.33%,43.29%,5124
4,2021-12-31,4494,4494,42.54%,3733,760.41,485.4,-64.88,593.68,166.73,...,3.71%,2.40%,3.44%,303.73,6.76%,137,166.73,3.71%,34.00%,4605
5,2020-12-31,3153,3153,-12.96%,2661,491.38,395.11,-37.87,513.24,-21.86,...,-0.69%,-0.89%,7.81%,116.15,3.68%,138,-21.86,-0.69%,-,3238

##### Cash Flow Statement:

In [10]:
cf_trsp=cash_flow_statement.transpose().reset_index(drop=False)
# sets first row as the actual column names:
cf_trsp.columns=cf_trsp.iloc[0]
# Remove first row:
cf_trsp=cf_trsp.drop(0)
cf_trsp

,Fiscal Year,Net Income,Depreciation & Amortization,Other Amortization,Loss (Gain) From Sale of Assets,Other Operating Activities,Change in Other Net Operating Assets,Operating Cash Flow,Operating Cash Flow Growth,Capital Expenditures,...,Net Cash Flow,Free Cash Flow,Free Cash Flow Growth,Free Cash Flow Margin,Free Cash Flow Per Share,Cash Interest Paid,Cash Income Tax Paid,Levered Free Cash Flow,Unlevered Free Cash Flow,Change in Net Working Capital
1,2024,141.24,145.83,-,-0.15,11.82,-34.31,264.42,-12.82%,-200.95,...,-44.72,63.47,-5.70%,1.16%,16.27,15.59,78.51,39.53,49.27,34.55
2,2023,65.08,143.22,2,-0.48,34.88,58.6,303.31,63.01%,-236,...,-83.5,67.31,74.11%,1.35%,17.26,34.3,41.89,19.69,41.13,-58.82
3,2022,85.93,164.15,2,0.08,-8.76,-57.33,186.07,-25.91%,-147.41,...,-128.24,38.66,-75.01%,0.79%,9.91,12.55,64.51,56.26,64.1,56.39
4,2021,107.77,149.7,1.6,-1.17,-5.75,-0.99,251.15,-34.64%,-96.47,...,114.13,154.68,-37.16%,3.44%,39.66,9.08,75.66,158.73,164.4,-5.36
5,2020,-28.05,150.8,1.6,-1.96,-1.83,263.71,384.27,-11.03%,-138.13,...,312.29,246.14,-35.17%,7.81%,63.11,8.44,18.04,264.51,269.78,-269.17

In [11]:
# Change data type of fiscal year:
cf_trsp['Fiscal Year']=pd.to_datetime(cf_trsp['Fiscal Year'], errors='coerce')
# Set the date to December 31 of the year for all valid dates:
cf_trsp['Fiscal Year']=cf_trsp['Fiscal Year'].dt.year.astype(str)+'-12-31'
# Convert the resulting strings back to datetime:
cf_trsp['Fiscal Year']=pd.to_datetime(cf_trsp['Fiscal Year'],errors='coerce')
cf_trsp

,Fiscal Year,Net Income,Depreciation & Amortization,Other Amortization,Loss (Gain) From Sale of Assets,Other Operating Activities,Change in Other Net Operating Assets,Operating Cash Flow,Operating Cash Flow Growth,Capital Expenditures,...,Net Cash Flow,Free Cash Flow,Free Cash Flow Growth,Free Cash Flow Margin,Free Cash Flow Per Share,Cash Interest Paid,Cash Income Tax Paid,Levered Free Cash Flow,Unlevered Free Cash Flow,Change in Net Working Capital
1,2024-12-31,141.24,145.83,-,-0.15,11.82,-34.31,264.42,-12.82%,-200.95,...,-44.72,63.47,-5.70%,1.16%,16.27,15.59,78.51,39.53,49.27,34.55
2,2023-12-31,65.08,143.22,2,-0.48,34.88,58.6,303.31,63.01%,-236,...,-83.5,67.31,74.11%,1.35%,17.26,34.3,41.89,19.69,41.13,-58.82
3,2022-12-31,85.93,164.15,2,0.08,-8.76,-57.33,186.07,-25.91%,-147.41,...,-128.24,38.66,-75.01%,0.79%,9.91,12.55,64.51,56.26,64.1,56.39
4,2021-12-31,107.77,149.7,1.6,-1.17,-5.75,-0.99,251.15,-34.64%,-96.47,...,114.13,154.68,-37.16%,3.44%,39.66,9.08,75.66,158.73,164.4,-5.36
5,2020-12-31,-28.05,150.8,1.6,-1.96,-1.83,263.71,384.27,-11.03%,-138.13,...,312.29,246.14,-35.17%,7.81%,63.11,8.44,18.04,264.51,269.78,-269.17

In [12]:
rat_trsp=ratios_statement.transpose().reset_index(drop=False)
rat_trsp.columns=rat_trsp.iloc[0]
rat_trsp=rat_trsp.drop([0,1]).reset_index(drop=True)
# Set new index starting from 1
rat_trsp.index = rat_trsp.index + 1
rat_trsp

,Fiscal Year,Market Capitalization,Market Cap Growth,Enterprise Value,Last Close Price,PE Ratio,Forward PE,PS Ratio,PB Ratio,P/TBV Ratio,...,Return on Equity (ROE),Return on Assets (ROA),Return on Capital (ROIC),Return on Capital Employed (ROCE),Earnings Yield,FCF Yield,Dividend Yield,Payout Ratio,Buyback Yield / Dilution,Total Shareholder Return
1,2024,3837,49.08%,3171,983.90,27.17,46.41,0.70,2.04,2.05,...,7.67%,2.73%,7.12%,9.50%,3.68%,1.65%,3.96%,57.99%,-0.01%,3.95%
2,2023,2574,26.92%,1902,644.65,39.55,28.08,0.52,1.42,1.42,...,3.56%,1.54%,3.77%,5.00%,2.53%,2.61%,3.26%,179.79%,-,3.26%
3,2022,2028,-15.45%,1162,482.47,23.60,14.61,0.42,1.10,1.10,...,4.61%,2.40%,5.14%,6.80%,4.24%,1.91%,6.22%,172.47%,-,6.22%
4,2021,2399,105.00%,1608,541.70,22.26,25.91,0.53,1.27,1.27,...,5.83%,2.72%,5.29%,6.80%,4.49%,6.45%,7.02%,25.30%,-,7.02%
5,2020,1170,20.00%,549,261.18,-,-,0.37,0.65,0.65,...,-1.52%,-0.37%,-0.71%,-,-2.40%,21.04%,2.68%,-,-,2.68%

In [13]:
rat_trsp['Fiscal Year']=pd.to_datetime(rat_trsp['Fiscal Year'],errors='coerce')
rat_trsp['Fiscal Year']=rat_trsp['Fiscal Year'].dt.year.astype(int).astype(str)+'-12-31'
rat_trsp['Fiscal Year']=pd.to_datetime(rat_trsp['Fiscal Year'],errors='coerce')
rat_trsp

,Fiscal Year,Market Capitalization,Market Cap Growth,Enterprise Value,Last Close Price,PE Ratio,Forward PE,PS Ratio,PB Ratio,P/TBV Ratio,...,Return on Equity (ROE),Return on Assets (ROA),Return on Capital (ROIC),Return on Capital Employed (ROCE),Earnings Yield,FCF Yield,Dividend Yield,Payout Ratio,Buyback Yield / Dilution,Total Shareholder Return
1,2024-12-31,3837,49.08%,3171,983.90,27.17,46.41,0.70,2.04,2.05,...,7.67%,2.73%,7.12%,9.50%,3.68%,1.65%,3.96%,57.99%,-0.01%,3.95%
2,2023-12-31,2574,26.92%,1902,644.65,39.55,28.08,0.52,1.42,1.42,...,3.56%,1.54%,3.77%,5.00%,2.53%,2.61%,3.26%,179.79%,-,3.26%
3,2022-12-31,2028,-15.45%,1162,482.47,23.60,14.61,0.42,1.10,1.10,...,4.61%,2.40%,5.14%,6.80%,4.24%,1.91%,6.22%,172.47%,-,6.22%
4,2021-12-31,2399,105.00%,1608,541.70,22.26,25.91,0.53,1.27,1.27,...,5.83%,2.72%,5.29%,6.80%,4.49%,6.45%,7.02%,25.30%,-,7.02%
5,2020-12-31,1170,20.00%,549,261.18,-,-,0.37,0.65,0.65,...,-1.52%,-0.37%,-0.71%,-,-2.40%,21.04%,2.68%,-,-,2.68%

### Preprocessing:

In [14]:
# Create new variable:
 ## activity ratios:
revenue=inc_trsp['Revenue'].str.replace(',','').astype(float)
cogs=inc_trsp['Cost of Revenue'].str.replace(',','').astype(float)
receivable=bs_trsp['Receivables'].str.replace(',','').astype(float)
inventory=bs_trsp['Inventory'].str.replace(',','').astype(float)
payable=bs_trsp['Accounts Payable'].str.replace(',','').astype(float)
current_assets=bs_trsp['Total Current Assets'].str.replace(',','').astype(float)
current_liabilities=bs_trsp['Total Current Liabilities'].str.replace(',','').astype(float)
total_assets=bs_trsp['Total Assets'].str.replace(',','').astype(float)
total_liabilities=bs_trsp['Total Liabilities'].str.replace(',','').astype(float)
total_equity=bs_trsp['Shareholders\' Equity'].str.replace(',','').astype(float)
 ##liquidity ratios:
cash_equivalents=bs_trsp['Cash & Equivalents'].str.replace(',','').astype(float)
operating_cash_flow=cf_trsp['Operating Cash Flow'].str.replace(',','').astype(float)
investing_cash_flow=cf_trsp['Investing Cash Flow'].str.replace(',','').astype(float)
financing_cash_flow=cf_trsp['Financing Cash Flow'].str.replace(',','').astype(float)
net_cash_flow=cf_trsp['Net Cash Flow'].str.replace(',','').astype(float)
 ##Solvency ratios:
total_debt=bs_trsp['Total Debt'].str.replace(',','').astype(float)
ebit=inc_trsp['EBIT'].str.replace(',','').astype(float)
interest_expenses=inc_trsp['Interest Expense'].str.replace(',','').astype(float).abs() #abs() is absolute number
 ##Profitability ratios:
gross_profit=inc_trsp['Gross Profit'].str.replace(',','').astype(float)
ebt=inc_trsp['Pretax Income'].str.replace(',','').astype(float)
net_income=inc_trsp['Net Income'].str.replace(',','').astype(float)
roce = rat_trsp['Return on Capital Employed (ROCE)'].str.replace('%', '',regex=False).replace('-',np.nan).astype(float) / 100
roic=rat_trsp['Return on Capital (ROIC)'].str.replace(',','').str.replace('%','').replace('-',np.nan).astype(float)/100
 ##Valuation ratios:
eps=inc_trsp['EPS (Basic)'].str.replace(',','').astype(float)
pe=rat_trsp['PE Ratio'].str.replace(',','').replace('-',np.nan).astype(float)
pb=rat_trsp['PB Ratio'].str.replace(',','').replace('-',np.nan).astype(float)
ps=rat_trsp['PS Ratio'].str.replace(',','').replace('-',np.nan).astype(float)
ev_ebitda=rat_trsp['EV/EBITDA Ratio'].str.replace(',','').astype(float)
dividend_yield=rat_trsp['Dividend Yield'].str.replace(',','').str.replace('%','').astype(float)/100

#### 0- Overview:

In [15]:
overview=inc_trsp[['Fiscal Year']].copy()
overview['Revenue']=revenue
overview['COGS']=cogs
overview['Gross Profit']=gross_profit
overview['Operating Income(EBIT)']=ebit
overview['Net Income']=net_income
overview['Total Assets']=total_assets
overview['Total liabilities']=total_liabilities
overview['Current Assets']=current_assets
overview['Current Liabilities']=current_liabilities
overview['Operating CF']=operating_cash_flow
overview['Investing CF']=investing_cash_flow
overview['Financing CF']=financing_cash_flow
overview['Net Cash Flow']=net_cash_flow

overview

,Fiscal Year,Revenue,COGS,Gross Profit,Operating Income(EBIT),Net Income,Total Assets,Total liabilities,Current Assets,Current Liabilities,Operating CF,Investing CF,Financing CF,Net Cash Flow
1,2024-12-31,5495.0,4391.0,1103.00,222.33,141.24,5306.0,3426.0,3676.0,2953.0,264.42,-216.38,-92.77,-44.72
2,2023-12-31,4996.0,4088.0,907.90,116.94,65.08,4883.0,3067.0,3309.0,2566.0,303.31,-269.83,-116.98,-83.50
3,2022-12-31,4888.0,4286.0,602.19,162.79,85.93,4581.0,2734.0,3092.0,2192.0,186.07,-159.98,-154.33,-128.24
4,2021-12-31,4494.0,3733.0,760.41,166.73,107.77,3892.0,2002.0,2400.0,1451.0,251.15,-104.18,-32.84,114.13
5,2020-12-31,3153.0,2661.0,491.38,-21.86,-28.05,3781.0,1966.0,2242.0,1402.0,384.27,-143.94,71.95,312.29

#### 1- Activity Ratios:

In [16]:
# Create new data frame:
act_ratio=inc_trsp[['Fiscal Year']].copy()
act_ratio['Revenue']=revenue
act_ratio['COGS']= cogs
act_ratio['DSO']=(receivable/revenue)*365
act_ratio['DIO']=(inventory/cogs)*365
act_ratio['DPO']=(payable/cogs)*365
act_ratio['CCC']=act_ratio['DSO']+act_ratio['DIO']-act_ratio['DPO']
act_ratio['Working Capital']=current_assets - current_liabilities
act_ratio['Beginning Working Capital']=act_ratio['Working Capital'].shift(-1,fill_value=act_ratio['Working Capital'].iloc[-1])
act_ratio['Working Capital Turnover']=revenue/((act_ratio['Working Capital']+act_ratio['Beginning Working Capital'])/2)
act_ratio['Total Assets']=total_assets
act_ratio['Beginning Total Assets']=act_ratio['Total Assets'].shift(-1,fill_value=act_ratio['Total Assets'].iloc[-1])
act_ratio['Total Assets Turnover']=revenue/((act_ratio['Total Assets']+act_ratio['Beginning Total Assets'])/2)
act_ratio['Total Equity']=total_equity
act_ratio['Beginning Total Equity']=act_ratio['Total Equity'].shift(-1,fill_value=act_ratio['Total Equity'].iloc[-1])
act_ratio['Equity Turnover']=revenue/((act_ratio['Total Equity']+act_ratio['Beginning Total Equity'])/2)
act_ratio

,Fiscal Year,Revenue,COGS,DSO,DIO,DPO,CCC,Working Capital,Beginning Working Capital,Working Capital Turnover,Total Assets,Beginning Total Assets,Total Assets Turnover,Total Equity,Beginning Total Equity,Equity Turnover
1,2024-12-31,5495.0,4391.0,128.796178,84.122068,193.597130,19.321116,723.0,743.0,7.496589,5306.0,4883.0,1.078614,1879.0,1816.0,2.974290
2,2023-12-31,4996.0,4088.0,113.605885,87.113393,182.678571,18.040706,743.0,900.0,6.081558,4883.0,4581.0,1.055790,1816.0,1847.0,2.727819
3,2022-12-31,4888.0,4286.0,89.905892,86.182921,151.501400,24.587413,900.0,949.0,5.287182,4581.0,3892.0,1.153783,1847.0,1890.0,2.616002
4,2021-12-31,4494.0,3733.0,63.015699,62.693370,103.643182,22.065886,949.0,840.0,5.024036,3892.0,3781.0,1.171380,1890.0,1814.0,2.426566
5,2020-12-31,3153.0,2661.0,95.636251,75.213867,149.374295,21.475823,840.0,840.0,3.753571,3781.0,3781.0,0.833906,1814.0,1814.0,1.738148

#### 2- Liquidity Ratios:

In [17]:
liq_ratio=bs_trsp[['Fiscal Year']].copy()
liq_ratio['Current Ratio']=current_assets/current_liabilities
liq_ratio['Quick Ratio']=(current_assets-inventory)/current_liabilities
liq_ratio['Cash Ratio']=cash_equivalents/current_liabilities
liq_ratio['Operating Cash Flow']=operating_cash_flow/current_liabilities
liq_ratio

0 Fiscal Year  Current Ratio  Quick Ratio  Cash Ratio  Operating Cash Flow
1  2024-12-31       1.244836     0.902133    0.244975             0.089543
2  2023-12-31       1.289556     0.909326    0.299353             0.118203
3  2022-12-31       1.410584     0.948905    0.388522             0.084886
4  2021-12-31       1.654032     1.212136    0.675314             0.173088
5  2020-12-31       1.599144     1.208031    0.617511             0.274087

#### 3- Solvency Ratios:

In [18]:
solv_ratios=bs_trsp[['Fiscal Year']].copy()
solv_ratios['Debt to Equity (D/E)']=total_debt/total_equity
solv_ratios['Debt to Capital']=total_debt/(total_debt+total_equity)
solv_ratios['Debt to Assets']=total_debt/total_assets
solv_ratios['Finanicial Leverage']= total_assets /total_equity
solv_ratios['Interest Coverage']=ebit/interest_expenses
solv_ratios

,Fiscal Year,Debt to Equity (D/E),Debt to Capital,Debt to Assets,Finanicial Leverage,Interest Coverage
1,2024-12-31,0.053230,0.050540,0.018850,2.823842,14.261065
2,2023-12-31,0.060441,0.056996,0.022478,2.688877,3.409329
3,2022-12-31,0.059042,0.055750,0.023805,2.480238,12.971315
4,2021-12-31,0.061222,0.057690,0.029730,2.059259,18.362335
5,2020-12-31,0.067911,0.063592,0.032581,2.084344,-2.590047

#### 4- Profitability Ratios:

In [19]:
prof_ratios=bs_trsp[['Fiscal Year']].copy()
prof_ratios['Gross Profit Margin']=gross_profit/revenue
prof_ratios['Operating Profit Margin']=ebit/revenue
prof_ratios['Pre-tax Margin']=ebt/revenue
prof_ratios['Net Profit Margin']=net_income/revenue
prof_ratios['Return on Assets(ROA)']= net_income/total_assets
prof_ratios['Return on Equity(ROE)']=net_income/total_equity
prof_ratios['Return on Capital Employed(ROCE)']=roce
prof_ratios['Return on Invested Capital(ROIC)']=roic
prof_ratios

,Fiscal Year,Gross Profit Margin,Operating Profit Margin,Pre-tax Margin,Net Profit Margin,Return on Assets(ROA),Return on Equity(ROE),Return on Capital Employed(ROCE),Return on Invested Capital(ROIC)
1,2024-12-31,0.200728,0.040460,0.037944,0.025703,0.026619,0.075168,0.095,0.0712
2,2023-12-31,0.181725,0.023407,0.018627,0.013026,0.013328,0.035837,0.050,0.0377
3,2022-12-31,0.123198,0.033304,0.031078,0.017580,0.018758,0.046524,0.068,0.0514
4,2021-12-31,0.169206,0.037101,0.036433,0.023981,0.027690,0.057021,0.068,0.0529
5,2020-12-31,0.155845,-0.006933,-0.009711,-0.008896,-0.007419,-0.015463,NaN,-0.0071

#### 5- Valuation Ratios:

In [20]:
val_ratios=inc_trsp[['Fiscal Year']].copy()
val_ratios['EPS']=eps
val_ratios['Price to Earnings(P/E)']=pe
val_ratios['Price to Sales(P/S)']=ps
val_ratios['Price to Book(P/B)']=pb
val_ratios['EV/EBITDA']=ev_ebitda
val_ratios['Dividend Yield']=dividend_yield
val_ratios

,Fiscal Year,EPS,Price to Earnings(P/E),Price to Sales(P/S),Price to Book(P/B),EV/EBITDA,Dividend Yield
1,2024-12-31,36.21,27.17,0.70,2.04,8.62,0.0396
2,2023-12-31,16.69,39.55,0.52,1.42,7.74,0.0326
3,2022-12-31,22.03,23.60,0.42,1.10,3.71,0.0622
4,2021-12-31,27.63,22.26,0.53,1.27,5.30,0.0702
5,2020-12-31,-7.19,NaN,0.37,0.65,4.73,0.0268

In [21]:
data={
    'Balance Sheet':bs_trsp,
    'Income Statement':inc_trsp,
    'Cash Flow':cf_trsp,
    'Sonasid Overview':overview,
    'Sonasid Activity':act_ratio,
    'Sonasid Liquidity':liq_ratio,
    'Sonsid Solvency':solv_ratios,
    'Sonasid Profitability':prof_ratios,
    'Sonasid Valuation':val_ratios
}
file_name='Financial Ratios (Sonasid).xlsx'
with pd.ExcelWriter(file_name,engine='xlsxwriter') as writer:
    for name,df in data.items():
        df.to_excel(writer,sheet_name=name,index=False)
print(f"Excel File '{file_name}'saved successfully")

Excel File 'Financial Ratios (Sonasid).xlsx'saved successfully